openapi: 3.0.0
info:
  title: Badger API
  description: Documentation for the Badger REST API. More info at gobadger.me.
  version: 0.1

servers:
  - url: https://<event>.gobadger.me/api/v1

paths:
  /public/reset:
    $ref: "paths/public/reset.yaml#/reset"
  /user/user:
    $ref: "paths/user/user.yaml#/user"
  /user/announcement:
    $ref: "paths/user/announcement.yaml#/announcement"
  /user/submission/{code}:
    $ref: "paths/user/submission.yaml#/submission-code"
  /user/event:
    $ref: "paths/user/event.yaml#/event"
  /user/rsvp:
    $ref: "paths/user/rsvp.yaml#/rsvp"
  /user/rsvp/{eventId}:
    $ref: "paths/user/rsvp.yaml#/rsvp-eventId"
  /user/attendance:
    $ref: "paths/user/attendance.yaml#/attendance"
  /user/attendance/{code}:
    $ref: "paths/user/attendance.yaml#/attendance-code"
  /user/entitlement:
    $ref: "paths/user/entitlement.yaml#/entitlement"
  /user/redemption:
    $ref: "paths/user/redemption.yaml#/redemption"
  /user/reward:
    $ref: "paths/user/reward.yaml#/reward"
  /user/claim:
    $ref: "paths/user/claim.yaml#/claim"
  /user/claim/{rewardId}:
    $ref: "paths/user/claim.yaml#/claim-rewardId"
  /manage/code:
    $ref: "paths/manage/code.yaml#/code"
  /manage/code/{codeId}:
    $ref: "paths/manage/code.yaml#/code-codeId"
  /manage/submission:
    $ref: "paths/manage/submission.yaml#/submission"
  /manage/submission/{submissionId}:
    $ref: "paths/manage/submission.yaml#/submission-submissionId"
  /manage/announcement:
    $ref: "paths/manage/announcement.yaml#/announcement"
  /manage/announcement/{announcementId}:
    $ref: "paths/manage/announcement.yaml#/announcement-announcementId"
  /manage/event:
    $ref: "paths/manage/event.yaml#/event"
  /manage/event/{eventId}:
    $ref: "paths/manage/event.yaml#/event-eventId"
  /manage/rsvp:
    $ref: "paths/manage/rsvp.yaml#/rsvp"
  /manage/rsvp/{rsvpId}:
    $ref: "paths/manage/rsvp.yaml#/rsvp-rsvpId"
  /manage/attendance:
    $ref: "paths/manage/attendance.yaml#/attendance"
  /manage/attendance/{attendanceId}:
    $ref: "paths/manage/attendance.yaml#/attendance-attendanceId"
  /manage/entitlement:
    $ref: "paths/manage/entitlement.yaml#/entitlement"
  /manage/entitlement/{entitlementId}:
    $ref: "paths/manage/entitlement.yaml#/entitlement-entitlementId"
  /manage/redemption:
    $ref: "paths/manage/redemption.yaml#/redemption"
  /manage/redemption/{redemptionId}:
    $ref: "paths/manage/redemption.yaml#/redemption-redemptionId"
  /manage/reward:
    $ref: "paths/manage/reward.yaml#/reward"
  /manage/reward/{rewardId}:
    $ref: "paths/manage/reward.yaml#/reward-rewardId"
  /manage/claim:
    $ref: "paths/manage/claim.yaml#/claim"
  /manage/claim/{claimId}:
    $ref: "paths/manage/claim.yaml#/claim-claimId"
  /admin/user:
    $ref: "paths/admin/user.yaml#/user"
  /admin/user/{userId}:
    $ref: "paths/admin/user.yaml#/user-userId"
  /admin/policy:
    $ref: "paths/admin/policy.yaml#/policy"
  /admin/reset:
    $ref: "paths/admin/reset.yaml#/reset"
  /admin/reset/{resetId}:
    $ref: "paths/admin/reset.yaml#/reset-resetId"
  /admin/configure:
    $ref: "paths/admin/configure.yaml#/configure"
  /admin/configure/{configurationId}:
    $ref: "paths/admin/configure.yaml#/configure-configurationId"
  /admin/scanner:
    $ref: "paths/admin/scanner.yaml#/scanner"
  /scanner/scan:
    $ref: "paths/scanner/scan.yaml#/scan"
  /scanner/ping:
    $ref: "paths/scanner/ping.yaml#/ping"

components:
  schemas:
    UserForm:
      $ref: "schemas/User.yaml#/UserForm"
    User:
      $ref: "schemas/User.yaml#/User"
    UserPrivilegedForm:
      $ref: "schemas/User.yaml#/UserPrivilegedForm"
    UserPrivilegedView:
      $ref: "schemas/User.yaml#/UserPrivilegedView"
    CodeForm:
      $ref: "schemas/Code.yaml#/CodeForm"
    Code:
      $ref: "schemas/Code.yaml#/Code"
    SubmissionForm:
      $ref: "schemas/Submission.yaml#/SubmissionForm"
    Submission:
      $ref: "schemas/Submission.yaml#/Submission"
    AnnouncementForm:
      $ref: "schemas/Announcement.yaml#/AnnouncementForm"
    Announcement:
      $ref: "schemas/Announcement.yaml#/Announcement"
    EventForm:
      $ref: "schemas/Event.yaml#/EventForm"
    Event:
      $ref: "schemas/Event.yaml#/Event"
    RsvpForm:
      $ref: "schemas/Rsvp.yaml#/RsvpForm"
    Rsvp:
      $ref: "schemas/Rsvp.yaml#/Rsvp"
    AttendanceForm:
      $ref: "schemas/Attendance.yaml#/AttendanceForm"
    Attendance:
      $ref: "schemas/Attendance.yaml#/Attendance"
    EntitlementForm:
      $ref: "schemas/Entitlement.yaml#/EntitlementForm"
    Entitlement:
      $ref: "schemas/Entitlement.yaml#/Entitlement"
    RedemptionForm:
      $ref: "schemas/Redemption.yaml#/RedemptionForm"
    Redemption:
      $ref: "schemas/Redemption.yaml#/Redemption"
    RewardForm:
      $ref: "schemas/Reward.yaml#/RewardForm"
    Reward:
      $ref: "schemas/Reward.yaml#/Reward"
    ClaimForm:
      $ref: "schemas/Claim.yaml#/ClaimForm"
    Claim:
      $ref: "schemas/Claim.yaml#/Claim"
    Policy:
      $ref: "schemas/Policy.yaml#/Policy"
    SelfServiceResetForm:
      $ref: "schemas/Reset.yaml#/SelfServiceResetForm"
    ResetForm:
      $ref: "schemas/Reset.yaml#/ResetForm"
    Reset:
      $ref: "schemas/Reset.yaml#/Reset"
    ConfigurationForm:
      $ref: "schemas/Configuration.yaml#/ConfigurationForm"
    Configuration:
      $ref: "schemas/Configuration.yaml#/Configuration"
    Scanner:
      $ref: "schemas/Scanner.yaml#/Scanner"
    Scan:
      $ref: "schemas/Scan.yaml#/Scan"
    Ping:
      $ref: "schemas/Ping.yaml#/Ping"
